package com.dwarslooper.cactus.client.systems.localserver.instance;

import com.dwarslooper.cactus.client.CactusClient;
import com.dwarslooper.cactus.client.systems.ISerializable;
import com.dwarslooper.cactus.client.systems.config.TreeSerializerFilter;
import com.dwarslooper.cactus.client.systems.localserver.LocalServerManager;
import com.dwarslooper.cactus.client.systems.localserver.PlatformManager;
import com.dwarslooper.cactus.client.util.CactusConstants;
import com.dwarslooper.cactus.client.util.Utils;
import com.google.gson.JsonObject;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Locale;
import java.util.Optional;
import java.util.Scanner;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import net.minecraft.class_156;
import net.minecraft.class_2561;
import net.minecraft.class_403;
import net.minecraft.class_437;
import net.minecraft.class_156.class_158;
import org.jetbrains.annotations.NotNull;

public class LocalServer implements ISerializable<LocalServer> {
   public final ExecutorService loggerService = Executors.newSingleThreadExecutor();
   private final File serverDir;
   private String name;
   private PlatformManager.Platform platform;
   private boolean gui;
   private int port;
   private File serverJar;
   private Process serverProcess;
   private InputStream serverOutput;
   private OutputStream serverInput;
   private final List<String> logLines = new CopyOnWriteArrayList();

   public LocalServer(String name, PlatformManager.Platform platform, boolean gui, int port) {
      this.name = name;
      this.platform = platform;
      this.gui = gui;
      this.port = port;
      this.serverDir = new File(LocalServerManager.get().getDirectory(), LocalServerManager.get().formatToValidName(name).toLowerCase(Locale.ROOT));
      this.setup();
   }

   public LocalServer(JsonObject object, File dir) {
      this.fromJson(object);
      this.serverDir = dir;
      this.setup();
   }

   private void setup() {
      if (!this.serverDir.exists()) {
         this.serverDir.mkdirs();

         try {
            Utils.writeFile(new File(this.serverDir, "eula.txt"), "# Autogenerated by Cactus to avoid manual configuration.\n# Find the EULA here: https://aka.ms/MinecraftEULA\n\neula=true");
            Utils.writeFile(new File(this.serverDir, "server.properties"), "server-port=" + this.port);
            Utils.writeFile(new File(this.serverDir, ".csp"), LocalServerManager.get().gson.toJson(this.toJson(TreeSerializerFilter.ALL)));
         } catch (IOException var2) {
            CactusClient.getLogger().error("Failed to setup local server", var2);
         }
      }

      this.serverJar = new File(this.serverDir, "server.jar");
   }

   public void run() {
      CactusClient.getLogger().info("Starting up server instance");

      try {
         if (!this.serverJar.exists()) {
            class_437 current = CactusConstants.mc.field_1755;
            CactusConstants.mc.method_1507(new class_403(() -> {
               CactusConstants.mc.method_1507(current);
            }, class_2561.method_43470("§c§nServer JAR not found"), class_2561.method_43470("The JAR file required to run this server was not found. If you created this server with the \"Custom\" option you have to manually install your server software.\n\n§e§n" + this.getServerJar().getAbsolutePath())));
            throw new FileNotFoundException(this.serverJar.getAbsolutePath());
         }

         ProcessBuilder processBuilder = this.getProcessBuilder();
         this.serverProcess = processBuilder.start();
         this.serverInput = this.serverProcess.getOutputStream();
         this.serverOutput = this.serverProcess.getInputStream();
         this.loggerService.submit(() -> {
            Scanner scanner = new Scanner(this.getServerOutput());

            while(scanner.hasNextLine()) {
               this.logLines.add(scanner.nextLine());
            }

         });
      } catch (Exception var2) {
         CactusClient.getLogger().error("Failed to start local server", var2);
      }

   }

   @NotNull
   private ProcessBuilder getProcessBuilder() {
      Optional<String> command = ProcessHandle.current().info().command();
      ProcessBuilder processBuilder;
      if (command.isPresent()) {
         processBuilder = new ProcessBuilder(new String[]{(String)command.get(), "-jar", this.serverJar.getName(), this.gui ? "" : "nogui"});
      } else {
         class_158 os = class_156.method_668();
         boolean isUnix = os == class_158.field_1135 || os == class_158.field_1137 || os == class_158.field_1134;
         if (!isUnix) {
            processBuilder = new ProcessBuilder(new String[]{"java", "-jar", this.serverJar.getName(), this.gui ? "" : "nogui"});
         } else {
            processBuilder = new ProcessBuilder(new String[]{"bash", "-l", "-c", "java", "-jar", this.serverJar.getName(), this.gui ? "" : "nogui"});
         }
      }

      processBuilder.directory(this.serverDir);
      return processBuilder;
   }

   public void sendCommand(String command) {
      if (this.isOnline()) {
         try {
            this.serverInput.write((command + "\n").getBytes(StandardCharsets.UTF_8));
            this.serverInput.flush();
         } catch (Exception var3) {
            CactusClient.getLogger().error("Failed to send command to local server", var3);
         }

         class_156.method_668();
      }
   }

   public synchronized CompletableFuture<Void> scheduleStop() {
      this.sendCommand("stop");
      return CompletableFuture.runAsync(() -> {
         if (this.serverProcess != null) {
            try {
               if (!this.serverProcess.waitFor(10L, TimeUnit.SECONDS)) {
                  this.serverProcess.destroyForcibly();
               }
            } catch (InterruptedException var2) {
               this.serverProcess.destroyForcibly();
               Thread.currentThread().interrupt();
            }

            this.serverProcess = null;
            this.logLines.clear();
         }

      });
   }

   public void shutdownInstantly() {
      if (this.serverProcess != null) {
         if (this.serverProcess.isAlive()) {
            this.serverProcess.destroy();
         }

         this.serverProcess = null;
      }
   }

   public boolean isOnline() {
      return this.getServerProcess() != null && this.serverProcess.isAlive();
   }

   public Process getServerProcess() {
      return this.serverProcess;
   }

   public OutputStream getServerInput() {
      return this.serverInput;
   }

   public InputStream getServerOutput() {
      return this.serverOutput;
   }

   public String getName() {
      return this.name;
   }

   public File getServerJar() {
      return this.serverJar;
   }

   public File getServerDir() {
      return this.serverDir;
   }

   public PlatformManager.Platform getPlatform() {
      return this.platform;
   }

   public boolean isGui() {
      return this.gui;
   }

   public int getPort() {
      return this.port;
   }

   public List<String> getLog() {
      return this.logLines;
   }

   public String toString() {
      String var10000 = this.name;
      return "LocalServer{name='" + var10000 + "', platform=" + String.valueOf(this.platform) + ", gui=" + this.gui + ", port=" + this.port + ", serverJar=" + String.valueOf(this.serverJar) + ", serverDir=" + String.valueOf(this.serverDir) + ", serverProcess=" + String.valueOf(this.serverProcess) + ", serverOutput=" + String.valueOf(this.serverOutput) + ", serverInput=" + String.valueOf(this.serverInput) + "}";
   }

   public JsonObject toJson(TreeSerializerFilter filter) {
      JsonObject object = new JsonObject();
      object.addProperty("name", this.name);
      object.addProperty("platform", this.platform.name());
      object.addProperty("port", this.port);
      object.addProperty("gui", this.gui);
      return object;
   }

   public LocalServer fromJson(JsonObject object) {
      this.name = object.get("name").getAsString();
      this.platform = PlatformManager.Platform.valueOf(object.get("platform").getAsString());
      this.gui = object.get("gui").getAsBoolean();
      this.port = object.get("port").getAsInt();
      return this;
   }
}
